package com.codegym.fashionshop.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity class representing a notification in the system.
 * <p>
 * This class maps to the {@code notification} table in the database and contains details about a notification,
 * such as its creation date, topic, and content.
 * </p>
 *
 * @author NhiNTY
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "notification")
public class Notification {

    /**
     * Unique identifier for the notification.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "notif_id")
    private Long notifId;

    /**
     * Date and time when the notification was created.
     */
    @Column(name = "create_date")
    private LocalDateTime createDate;

    /**
     * Topic or subject of the notification.
     * This field cannot be null or blank and must be 255 characters or less.
     */
    @NotNull(message = "Không được để trống")
    @NotBlank(message = "Không được để trống")
    @Size(max = 255, message = "Tiêu đề tối đa 255 ký tự.")
    private String topic;

    /**
     * Content of the notification.
     * This field cannot be null or blank and is stored as a text type in the database.
     */
    @NotNull(message = "Không được để trống")
    @NotBlank(message = "Không được để trống")
    @Column(name = "content", columnDefinition = "TEXT")
    private String content;
}
